# Generated by Django 4.2.7 on 2025-12-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("STAFF", "Staff"),
                    ("CLIENTE", "Cliente"),
                ],
                default="CLIENTE",
                max_length=10,
            ),
        ),
    ]
