# Generated by Django 6.0.2 on 2026-02-28 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="subordinates",
            field=models.ManyToManyField(
                blank=True, related_name="superiors", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("JEFE", "Jefe"),
                    ("COORDINADOR", "Coordinador"),
                    ("COBRADOR", "Cobrador"),
                ],
                default="COBRADOR",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="users_user",
        ),
    ]
